create table if not exists users
(
    id          int generated by default as identity primary key,
    email       varchar,
    login       varchar,
    name        varchar,
    birthday    Date
);

create table if not exists films
(
    id           int generated by default as identity primary key,
    name         varchar,
    description  varchar,
    release_date Date,
    duration int,
    mpa varchar
);

create table if not exists film_likes
(
    film_id           identity primary key,
    like_user_id int,
    FOREIGN KEY (film_id) REFERENCES films(id)
);

create table if not exists friends
(
    user_id           identity primary key,
    friend_user_id    int,
    FOREIGN KEY (user_id) REFERENCES users(id)
);